name: Check source code before merge

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint
      run: npm run lint
